name: ksqlDB Migrations Validate
description: validate ksqlDB schema with GitHub actions
inputs:
  config:
    description: Path to config file
    default: /github/workspace/ksql-migrations.properties
runs:
  using: docker
  image: docker://confluentinc/cp-ksql-cli:5.4.10
  args:
    - ksql-migrations --config-file ${{ inputs.config }} validate