name: ksqlDB Migrations Apply
description: apply ksqlDB schema with GitHub actions
inputs:
  config:
    description: Path to config file
    default: /github/workspace/ksql-migrations.properties
runs:
  using: docker
  image: docker://confluentinc/cp-ksqldb-server:6.2.0
  args:
    - ksql-migrations -c ${{ inputs.config }} apply -a