CREATE OR REPLACE STREAM AGGREGATED_TASK_PO_EXPORT AS
SELECT
    ROWKEY AS id,
    t.payload->after->id AS task_id,
    t.payload->after->parent_id AS task_parent_id,
    t.payload->after->party_id AS task_party_id,
    t.payload->after->party_name AS task_party_name,
    t.payload->after->external_id AS task_external_id,
    t.payload->after->search_code AS task_search_code,
    t.payload->after->type AS task_type,
    t.payload->after->status AS task_status,
    t.payload->after->sub_status AS task_sub_status,
    t.payload->after->sla_start_date AS task_sla_start_date,
    t.payload->after->sla_end_date AS task_sla_end_date,
    t.payload->after->sla_warn_level AS task_sla_warn_level,
    t.payload->after->plan_start_date AS task_plan_start_date,
    t.payload->after->wish_date AS task_wish_date,
    t.payload->after->plan_complete_date AS task_plan_complete_date,
    t.payload->after->task_body AS task_body,
    t.payload->after->reason_code AS task_reason_code,
    t.payload->after->reason_text AS task_reason_text,
    t.payload->after->branch AS task_branch,
    t.payload->after->created_at AS task_created_at,
    t.payload->after->created_by AS task_created_by,
    t.payload->after->updated_at AS task_updated_at,
    t.payload->after->updated_by AS task_updated_by,
    t.payload->after->revision AS task_revision,
    t.payload->after->org_id AS task_org_id,
    t.payload->after->attachments AS task_attachments,
    t.payload->after->comments AS task_comments,
    t.payload->after->category AS task_category,
    t.payload->after->priority AS task_priority,
    t.payload->after->completed AS task_completed,
    t.payload->after->coordinates AS task_coordinates,
    t.payload->after->ac_info AS task_ac_info,
    t.payload->after->dhid AS task_dhid,
    t.payload->after->version AS task_version,
    t.payload->after->deadlines AS task_deadlines,
    t.payload->after->group_id AS task_group_id,
    t.payload->after->delivered_at AS task_delivered_at,
    t.payload->after->party_code AS task_party_code,
    t.payload->after->network_owner_code AS task_network_owner_code,
    t.payload->after->closed_at AS task_closed_at,
    t.payload->after->area_code AS task_area_code,
    t.payload->after->sub_type AS task_sub_type,
    t.payload->after->is_created_from_dynamic_workflow AS task_is_created_from_dynamic_workflow ,
    t.payload->after->system_id AS task_system_id,
    t.payload->source->lsn AS task_source_lsn,
    t.payload->op AS task_op,
    t.payload->ts_ms AS task_ts_ms,

    v.payload->after->id AS version_id,
    v.payload->after->revision AS version_revision,
    v.payload->after->task_id AS version_task_id,
    v.payload->after->task_type AS version_task_type,
    v.payload->after->old_main_status AS version_old_main_status,
    v.payload->after->old_main_status_reason AS version_old_main_status_reason,
    v.payload->after->new_main_status AS version_new_main_status,
    v.payload->after->new_main_status_reason AS version_new_main_status_reason,
    v.payload->after->new_sub_status AS version_new_sub_status,
    v.payload->after->task_body AS version_task_body,
    v.payload->after->created_at AS version_created_at,
    v.payload->after->created_by AS version_created_by,
    v.payload->after->updated_at AS version_updated_at,
    v.payload->after->updated_by AS version_updated_by,
    v.payload->after->attachments AS version_attachments,
    v.payload->after->comments AS version_comments,
    v.payload->source->lsn AS version_source_lsn,
    v.payload->op AS version_op,
    v.payload->ts_ms AS version_ts_ms,

    c.payload->after->note AS comment_note,
    c.payload->after->created_at AS comment_created_at,
    c.payload->after->user_id AS comment_user_id,
    c.payload->after->party_id AS comment_party_id,
    c.payload->after->task_id AS comment_task_id,
    c.payload->after->privacy_level AS comment_privacy_level,
    c.payload->after->author AS comment_author,
    c.payload->after->id AS comment_id,
    c.payload->source->lsn AS comment_source_lsn,
    c.payload->op AS comment_op,
    c.payload->ts_ms AS comment_ts_ms,

    h.payload->after->id AS history_id,
    h.payload->after->record_id AS history_record_id,
    h.payload->after->model_type AS history_model_type,
    h.payload->after->changes_set AS history_changes_set,
    h.payload->after->before_changes AS history_before_changes,
    h.payload->after->after_changes AS history_after_changes,
    h.payload->after->action AS history_action,
    h.payload->after->remark AS history_remark,
    h.payload->after->created_at AS history_created_at,
    h.payload->after->created_by AS history_created_by,
    h.payload->after->updated_by_file AS history_updated_by_file,
    h.payload->source->lsn AS history_source_lsn,
    h.payload->op AS history_op,
    h.payload->ts_ms AS history_ts_ms
 
FROM TASKS_STREAM t
LEFT JOIN TASK_VERSIONS_STREAM v within 2 seconds ON t.payload->after->id = v.payload->after->task_id
LEFT JOIN TASK_COMMENTS_STREAM c within 2 seconds ON t.payload->after->id = c.payload->after->task_id
LEFT JOIN TASK_FIELDS_HISTORIES_STREAM h within 2 seconds ON t.payload->after->id = CAST(h.payload->after->record_id AS BIGINT)
EMIT CHANGES;