on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Replace envs
      #   uses: franzbischoff/replace_envs@v1
      #   env:
      #     KSQLDB_ENDPOINT: http://35.198.247.201:8088
      #   with:
      #     from_file: 'ksql-migrations.properties'
      #     to_file: 'ksql-migrations.properties'
      #     commit: 'false'



      - name: ksqlDB migrations validate
        uses: ./.github/actions/ksqldb-migrations-validate

      - name: ksqlDB migrations apply
        if: github.event_name == 'push'
        uses: ./.github/actions/ksqldb-migrations-apply
      
